 const CHANGING_DATE = 'CHANGING_DATE';
 const CHANGING_NUMBER = 'CHANGING_NUMBER';
 const CHANGING_CVC = 'CHANGING_CVC';
 const CHANGING_NAME = 'CHANGING_NAME';
 const CHANGING_CARD_TYPE = "CHANGING_CARD_TYPE";